import { Product, StockMovement, Alert, Category, StorageLocation, ProductNote, Licensor, Licensee, Manufacturer } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'フィギュア' },
  { id: '2', name: 'ぬいぐるみ' },
  { id: '3', name: 'アパレル' },
  { id: '4', name: '文具' },
  { id: '5', name: 'アクセサリー' },
];

export const storageLocations: StorageLocation[] = [
  { id: '1', name: '倉庫A-1', code: 'WH-A-1' },
  { id: '2', name: '倉庫A-2', code: 'WH-A-2' },
  { id: '3', name: '倉庫B-1', code: 'WH-B-1' },
  { id: '4', name: '倉庫B-2', code: 'WH-B-2' },
  { id: '5', name: '倉庫C-1', code: 'WH-C-1' },
];

export const licensors: Licensor[] = [
  { id: '1', name: '株式会社アニメ制作', contactInfo: 'anime@example.com' },
  { id: '2', name: '株式会社キャラクター企画', contactInfo: 'character@example.com' },
  { id: '3', name: '株式会社IP保有', contactInfo: 'ip@example.com' },
  { id: '4', name: '株式会社制作委員会', contactInfo: 'committee@example.com' },
  { id: '5', name: '株式会社版元', contactInfo: 'publisher@example.com' },
];

export const licensees: Licensee[] = [
  { id: '1', name: '株式会社グッズ企画', contactInfo: 'goods@example.com' },
  { id: '2', name: '株式会社ぬいぐるみ販売', contactInfo: 'plush@example.com' },
  { id: '3', name: '株式会社アパレル', contactInfo: 'apparel@example.com' },
  { id: '4', name: '株式会社文具販売', contactInfo: 'stationery@example.com' },
  { id: '5', name: '株式会社グッズ製作', contactInfo: 'production@example.com' },
];

export const manufacturers: Manufacturer[] = [
  { id: '1', name: '株式会社製造工場', contactInfo: 'factory@example.com' },
  { id: '2', name: '株式会社縫製工場', contactInfo: 'sewing@example.com' },
  { id: '3', name: '株式会社印刷工場', contactInfo: 'printing@example.com' },
  { id: '4', name: '株式会社成型工場', contactInfo: 'molding@example.com' },
  { id: '5', name: '株式会社組立工場', contactInfo: 'assembly@example.com' },
];

export const products: Product[] = [
  {
    id: '1',
    sku: 'A001',
    name: 'キャラクターA フィギュア 限定版',
    description: '人気キャラクターAの限定フィギュア',
    categoryId: '1',
    categoryName: 'フィギュア',
    currentStock: 100,
    storageLocationId: '1',
    storageLocationName: '倉庫A-1',
    stockBreakdown: {
      new: 95,
      used: 3,
      damaged: 2,
    },
    usedStockImages: ['https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=400&h=400&fit=crop'],
    damagedStockImages: ['https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=400&h=400&fit=crop&brightness=0.8'],
    imageUrl: 'https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 500,
      salesRegions: ['日本', 'アメリカ'],
      salesStartDate: '2024-01-01',
      salesEndDate: '2026-06-30',
      licensorId: '1',
      licensorName: '株式会社アニメ制作',
      licenseeId: '1',
      licenseeName: '株式会社グッズ企画',
      manufacturerId: '1',
      manufacturerName: '株式会社製造工場',
    },
    createdBy: '田中太郎',
    createdAt: '2024-01-15T09:00:00Z',
    updatedBy: '山田花子',
    updatedAt: '2025-10-05T15:30:00Z',
  },
  {
    id: '2',
    sku: 'B002',
    name: 'キャラクターB ぬいぐるみ',
    description: 'もふもふのキャラクターBぬいぐるみ',
    categoryId: '2',
    categoryName: 'ぬいぐるみ',
    currentStock: 20,
    storageLocationId: '2',
    storageLocationName: '倉庫A-2',
    stockBreakdown: {
      new: 18,
      used: 2,
      damaged: 0,
    },
    usedStockImages: ['https://images.unsplash.com/photo-1530325553241-4f6e7690cf36?w=400&h=400&fit=crop'],
    imageUrl: 'https://images.unsplash.com/photo-1530325553241-4f6e7690cf36?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 1000,
      salesRegions: ['日本'],
      salesStartDate: '2024-02-01',
      salesEndDate: '2025-11-05',
      licensorId: '2',
      licensorName: '株式会社キャラクター企画',
      licenseeId: '2',
      licenseeName: '株式会社ぬいぐるみ販売',
      manufacturerId: '2',
      manufacturerName: '株式会社縫製工場',
    },
    createdBy: '佐藤次郎',
    createdAt: '2024-02-01T10:30:00Z',
    updatedBy: '鈴木一郎',
    updatedAt: '2025-10-06T11:15:00Z',
  },
  {
    id: '3',
    sku: 'C003',
    name: 'キャラクターC Tシャツ',
    description: 'コラボTシャツ Lサイズ',
    categoryId: '3',
    categoryName: 'アパレル',
    currentStock: 0,
    storageLocationId: '3',
    storageLocationName: '倉庫B-1',
    stockBreakdown: {
      new: 0,
      used: 0,
      damaged: 0,
    },
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 300,
      salesRegions: ['日本', '中国', '韓国'],
      salesStartDate: '2024-03-01',
      salesEndDate: '2025-10-01',
      licensorId: '3',
      licensorName: '株式会社IP保有',
      licenseeId: '3',
      licenseeName: '株式会社アパレル',
      manufacturerId: '3',
      manufacturerName: '株式会社印刷工場',
    },
    createdBy: '高橋美咲',
    createdAt: '2024-03-01T14:00:00Z',
    updatedBy: '高橋美咲',
    updatedAt: '2025-09-20T09:45:00Z',
  },
  {
    id: '4',
    sku: 'D004',
    name: 'キャラクターD クリアファイル',
    description: 'A4サイズクリアファイル',
    categoryId: '4',
    categoryName: '文具',
    currentStock: 250,
    storageLocationId: '4',
    storageLocationName: '倉庫B-2',
    stockBreakdown: {
      new: 250,
      used: 0,
      damaged: 0,
    },
    imageUrl: 'https://images.unsplash.com/photo-1587033411391-5d9e51cce126?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 2000,
      salesRegions: ['日本'],
      salesStartDate: '2024-04-01',
      salesEndDate: '2026-12-31',
      licensorId: '4',
      licensorName: '株式会社制作委員会',
      licenseeId: '4',
      licenseeName: '株式会社文具販売',
      manufacturerId: '4',
      manufacturerName: '株式会社成型工場',
    },
    createdBy: '伊藤健太',
    createdAt: '2024-04-01T11:00:00Z',
    updatedBy: '田中太郎',
    updatedAt: '2025-10-07T14:20:00Z',
  },
  {
    id: '5',
    sku: 'E005',
    name: 'キャラクターE アクリルキーホルダー',
    description: '限定デザインキーホルダー',
    categoryId: '5',
    categoryName: 'アクセサリー',
    currentStock: 80,
    storageLocationId: '5',
    storageLocationName: '倉庫C-1',
    stockBreakdown: {
      new: 80,
      used: 0,
      damaged: 0,
    },
    imageUrl: 'https://images.unsplash.com/photo-1611923134239-a8834dcbb462?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 500,
      salesRegions: ['日本', 'アメリカ', 'フランス'],
      salesStartDate: '2024-05-01',
      salesEndDate: '2025-10-25',
      licensorId: '5',
      licensorName: '株式会社版元',
      licenseeId: '5',
      licenseeName: '株式会社グッズ製作',
      manufacturerId: '5',
      manufacturerName: '株式会社組立工場',
    },
    createdBy: '渡辺京子',
    createdAt: '2024-05-01T13:00:00Z',
    updatedBy: '佐藤次郎',
    updatedAt: '2025-10-08T10:00:00Z',
  },
];

export const stockMovements: StockMovement[] = [
  {
    id: '1',
    productId: '1',
    productName: 'キャラクターA フィギュア 限定版',
    productSku: 'A001',
    movementType: 'in',
    quantity: 50,
    condition: 'new',
    reason: '仕入れ',
    createdBy: '山田太郎',
    createdAt: '2025-10-08T09:30:00Z',
  },
  {
    id: '2',
    productId: '2',
    productName: 'キャラクターB ぬいぐるみ',
    productSku: 'B002',
    movementType: 'out',
    quantity: 30,
    condition: 'new',
    reason: '販売',
    notes: 'イベント販売用',
    createdBy: '佐藤花子',
    createdAt: '2025-10-08T10:15:00Z',
  },
  {
    id: '3',
    productId: '4',
    productName: 'キャラクターD クリアファイル',
    productSku: 'D004',
    movementType: 'in',
    quantity: 100,
    condition: 'new',
    reason: '仕入れ',
    createdBy: '田中一郎',
    createdAt: '2025-10-08T11:00:00Z',
  },
  {
    id: '4',
    productId: '5',
    productName: 'キャラクターE アクリルキーホルダー',
    productSku: 'E005',
    movementType: 'out',
    quantity: 20,
    condition: 'new',
    reason: '販売',
    createdBy: '鈴木次郎',
    createdAt: '2025-10-07T16:45:00Z',
  },
];

export const alerts: Alert[] = [
  {
    id: '1',
    type: 'expiring',
    severity: 'warning',
    message: 'キャラクターE アクリルキーホルダーの販売期限が近づいています（17日後）',
    productId: '5',
    createdAt: '2025-10-08T00:00:00Z',
  },
  {
    id: '2',
    type: 'expired',
    severity: 'error',
    message: 'キャラクターC Tシャツの販売期限が切れています',
    productId: '3',
    createdAt: '2025-10-08T00:00:00Z',
  },
];

export const productNotes: ProductNote[] = [
  {
    id: '1',
    productId: '1',
    noteType: 'general',
    content: 'イベント用に追加発注予定。次回入庫は11月中旬を予定しています。',
    createdBy: 'user1',
    createdByName: '山田太郎',
    createdAt: '2025-10-05T10:30:00Z',
  },
  {
    id: '2',
    productId: '1',
    noteType: 'quality',
    content: 'ロットNo.1234について、塗装の色むらが一部あり。検品時に要確認。',
    createdBy: 'user2',
    createdByName: '佐藤花子',
    createdAt: '2025-10-03T14:20:00Z',
  },
  {
    id: '3',
    productId: '2',
    noteType: 'damage',
    content: '倉庫A-2の棚から落下により、3個のパッケージに軽微な破損あり。別途保管中。',
    attachments: [
      {
        url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=300&fit=crop',
        name: 'damage_report_001.jpg',
        type: 'image/jpeg',
      },
    ],
    createdBy: 'user3',
    createdByName: '田中一郎',
    createdAt: '2025-10-07T16:45:00Z',
  },
  {
    id: '4',
    productId: '2',
    noteType: 'handover',
    content: '在庫が少なくなっています。緊急発注の必要があります。発注担当者に連絡済み。',
    createdBy: 'user1',
    createdByName: '山田太郎',
    createdAt: '2025-10-08T09:00:00Z',
  },
  {
    id: '5',
    productId: '5',
    noteType: 'general',
    content: '人気商品のため、週末のイベント前に在庫確認を忘れずに。',
    createdBy: 'user2',
    createdByName: '佐藤花子',
    createdAt: '2025-10-06T11:00:00Z',
  },
];
