import { Product, StockMovement, Alert, Category, StorageLocation, ProductNote, Licensor, Licensee, Manufacturer, Stocktaking, StocktakingItem, User, UserRole, Report } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'フィギュア' },
  { id: '2', name: 'ぬいぐるみ' },
  { id: '3', name: 'アパレル' },
  { id: '4', name: '文具' },
  { id: '5', name: 'アクセサリー' },
];

export const storageLocations: StorageLocation[] = [
  { id: '1', name: '倉庫A-1', code: 'WH-A-1' },
  { id: '2', name: '倉庫A-2', code: 'WH-A-2' },
  { id: '3', name: '倉庫B-1', code: 'WH-B-1' },
  { id: '4', name: '倉庫B-2', code: 'WH-B-2' },
  { id: '5', name: '倉庫C-1', code: 'WH-C-1' },
];

export const licensors: Licensor[] = [
  { id: '1', name: '株式会社アニメ制作', contactInfo: 'anime@example.com' },
  { id: '2', name: '株式会社キャラクター企画', contactInfo: 'character@example.com' },
  { id: '3', name: '株式会社IP保有', contactInfo: 'ip@example.com' },
  { id: '4', name: '株式会社制作委員会', contactInfo: 'committee@example.com' },
  { id: '5', name: '株式会社版元', contactInfo: 'publisher@example.com' },
];

export const licensees: Licensee[] = [
  { id: '1', name: '株式会社グッズ企画', contactInfo: 'goods@example.com' },
  { id: '2', name: '株式会社ぬいぐるみ販売', contactInfo: 'plush@example.com' },
  { id: '3', name: '株式会社アパレル', contactInfo: 'apparel@example.com' },
  { id: '4', name: '株式会社文具販売', contactInfo: 'stationery@example.com' },
  { id: '5', name: '株式会社グッズ製作', contactInfo: 'production@example.com' },
];

export const manufacturers: Manufacturer[] = [
  { id: '1', name: '株式会社製造工場', contactInfo: 'factory@example.com' },
  { id: '2', name: '株式会社縫製工場', contactInfo: 'sewing@example.com' },
  { id: '3', name: '株式会社印刷工場', contactInfo: 'printing@example.com' },
  { id: '4', name: '株式会社成型工場', contactInfo: 'molding@example.com' },
  { id: '5', name: '株式会社組立工場', contactInfo: 'assembly@example.com' },
];

export const products: Product[] = [
  {
    id: '1',
    sku: 'A001',
    name: 'キャラクターA フィギュア 限定版',
    description: '人気キャラクターAの限定フィギュア',
    categoryId: '1',
    categoryName: 'フィギュア',
    currentStock: 100,
    storageLocationId: '1',
    storageLocationName: '倉庫A-1',
    stockBreakdown: {
      new: 95,
      used: 3,
      damaged: 2,
    },
    usedStockImages: ['https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=400&h=400&fit=crop'],
    damagedStockImages: ['https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=400&h=400&fit=crop&brightness=0.8'],
    imageUrl: 'https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 500,
      salesRegions: ['日本', 'アメリカ'],
      salesStartDate: '2024-01-01',
      salesEndDate: '2026-06-30',
      licensorId: '1',
      licensorName: '株式会社アニメ制作',
      licenseeId: '1',
      licenseeName: '株式会社グッズ企画',
      manufacturerId: '1',
      manufacturerName: '株式会社製造工場',
    },
    createdBy: '田中太郎',
    createdAt: '2024-01-15T09:00:00Z',
    updatedBy: '山田花子',
    updatedAt: '2025-10-05T15:30:00Z',
  },
  {
    id: '2',
    sku: 'B002',
    name: 'キャラクターB ぬいぐるみ',
    description: 'もふもふのキャラクターBぬいぐるみ',
    categoryId: '2',
    categoryName: 'ぬいぐるみ',
    currentStock: 20,
    storageLocationId: '2',
    storageLocationName: '倉庫A-2',
    stockBreakdown: {
      new: 18,
      used: 2,
      damaged: 0,
    },
    usedStockImages: ['https://images.unsplash.com/photo-1530325553241-4f6e7690cf36?w=400&h=400&fit=crop'],
    imageUrl: 'https://images.unsplash.com/photo-1530325553241-4f6e7690cf36?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 1000,
      salesRegions: ['日本'],
      salesStartDate: '2024-02-01',
      salesEndDate: '2025-11-05',
      licensorId: '2',
      licensorName: '株式会社キャラクター企画',
      licenseeId: '2',
      licenseeName: '株式会社ぬいぐるみ販売',
      manufacturerId: '2',
      manufacturerName: '株式会社縫製工場',
    },
    createdBy: '佐藤次郎',
    createdAt: '2024-02-01T10:30:00Z',
    updatedBy: '鈴木一郎',
    updatedAt: '2025-10-06T11:15:00Z',
  },
  {
    id: '3',
    sku: 'C003',
    name: 'キャラクターC Tシャツ',
    description: 'コラボTシャツ Lサイズ',
    categoryId: '3',
    categoryName: 'アパレル',
    currentStock: 0,
    storageLocationId: '3',
    storageLocationName: '倉庫B-1',
    stockBreakdown: {
      new: 0,
      used: 0,
      damaged: 0,
    },
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 300,
      salesRegions: ['日本', '中国', '韓国'],
      salesStartDate: '2024-03-01',
      salesEndDate: '2025-10-01',
      licensorId: '3',
      licensorName: '株式会社IP保有',
      licenseeId: '3',
      licenseeName: '株式会社アパレル',
      manufacturerId: '3',
      manufacturerName: '株式会社印刷工場',
    },
    createdBy: '高橋美咲',
    createdAt: '2024-03-01T14:00:00Z',
    updatedBy: '高橋美咲',
    updatedAt: '2025-09-20T09:45:00Z',
  },
  {
    id: '4',
    sku: 'D004',
    name: 'キャラクターD クリアファイル',
    description: 'A4サイズクリアファイル',
    categoryId: '4',
    categoryName: '文具',
    currentStock: 250,
    storageLocationId: '4',
    storageLocationName: '倉庫B-2',
    stockBreakdown: {
      new: 250,
      used: 0,
      damaged: 0,
    },
    imageUrl: 'https://images.unsplash.com/photo-1587033411391-5d9e51cce126?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 2000,
      salesRegions: ['日本'],
      salesStartDate: '2024-04-01',
      salesEndDate: '2026-12-31',
      licensorId: '4',
      licensorName: '株式会社制作委員会',
      licenseeId: '4',
      licenseeName: '株式会社文具販売',
      manufacturerId: '4',
      manufacturerName: '株式会社成型工場',
    },
    createdBy: '伊藤健太',
    createdAt: '2024-04-01T11:00:00Z',
    updatedBy: '田中太郎',
    updatedAt: '2025-10-07T14:20:00Z',
  },
  {
    id: '5',
    sku: 'E005',
    name: 'キャラクターE アクリルキーホルダー',
    description: '限定デザインキーホルダー',
    categoryId: '5',
    categoryName: 'アクセサリー',
    currentStock: 80,
    storageLocationId: '5',
    storageLocationName: '倉庫C-1',
    stockBreakdown: {
      new: 80,
      used: 0,
      damaged: 0,
    },
    imageUrl: 'https://images.unsplash.com/photo-1611923134239-a8834dcbb462?w=200&h=200&fit=crop',
    ipInfo: {
      productionQuantity: 500,
      salesRegions: ['日本', 'アメリカ', 'フランス'],
      salesStartDate: '2024-05-01',
      salesEndDate: '2025-10-25',
      licensorId: '5',
      licensorName: '株式会社版元',
      licenseeId: '5',
      licenseeName: '株式会社グッズ製作',
      manufacturerId: '5',
      manufacturerName: '株式会社組立工場',
    },
    createdBy: '渡辺京子',
    createdAt: '2024-05-01T13:00:00Z',
    updatedBy: '佐藤次郎',
    updatedAt: '2025-10-08T10:00:00Z',
  },
];

export const stockMovements: StockMovement[] = [
  {
    id: '1',
    productId: '1',
    productName: 'キャラクターA フィギュア 限定版',
    productSku: 'A001',
    movementType: 'in',
    quantity: 50,
    condition: 'new',
    reason: '仕入れ',
    createdBy: '山田太郎',
    createdAt: '2025-10-08T09:30:00Z',
  },
  {
    id: '2',
    productId: '2',
    productName: 'キャラクターB ぬいぐるみ',
    productSku: 'B002',
    movementType: 'out',
    quantity: 30,
    condition: 'new',
    reason: '販売',
    notes: 'イベント販売用',
    createdBy: '佐藤花子',
    createdAt: '2025-10-08T10:15:00Z',
  },
  {
    id: '3',
    productId: '4',
    productName: 'キャラクターD クリアファイル',
    productSku: 'D004',
    movementType: 'in',
    quantity: 100,
    condition: 'new',
    reason: '仕入れ',
    createdBy: '田中一郎',
    createdAt: '2025-10-08T11:00:00Z',
  },
  {
    id: '4',
    productId: '5',
    productName: 'キャラクターE アクリルキーホルダー',
    productSku: 'E005',
    movementType: 'out',
    quantity: 20,
    condition: 'new',
    reason: '販売',
    createdBy: '鈴木次郎',
    createdAt: '2025-10-07T16:45:00Z',
  },
];

export const alerts: Alert[] = [
  {
    id: '1',
    type: 'expiring',
    severity: 'warning',
    message: 'キャラクターE アクリルキーホルダーの販売期限が近づいています（17日後）',
    productId: '5',
    createdAt: '2025-10-08T00:00:00Z',
  },
  {
    id: '2',
    type: 'expired',
    severity: 'error',
    message: 'キャラクターC Tシャツの販売期限が切れています',
    productId: '3',
    createdAt: '2025-10-08T00:00:00Z',
  },
];

export const productNotes: ProductNote[] = [
  {
    id: '1',
    productId: '1',
    noteType: 'general',
    content: 'イベント用に追加発注予定。次回入庫は11月中旬を予定しています。',
    createdBy: 'user1',
    createdByName: '山田太郎',
    createdAt: '2025-10-05T10:30:00Z',
  },
  {
    id: '2',
    productId: '1',
    noteType: 'quality',
    content: 'ロットNo.1234について、塗装の色むらが一部あり。検品時に要確認。',
    createdBy: 'user2',
    createdByName: '佐藤花子',
    createdAt: '2025-10-03T14:20:00Z',
  },
  {
    id: '3',
    productId: '2',
    noteType: 'damage',
    content: '倉庫A-2の棚から落下により、3個のパッケージに軽微な破損あり。別途保管中。',
    attachments: [
      {
        url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=300&fit=crop',
        name: 'damage_report_001.jpg',
        type: 'image/jpeg',
      },
    ],
    createdBy: 'user3',
    createdByName: '田中一郎',
    createdAt: '2025-10-07T16:45:00Z',
  },
  {
    id: '4',
    productId: '2',
    noteType: 'handover',
    content: '在庫が少なくなっています。緊急発注の必要があります。発注担当者に連絡済み。',
    createdBy: 'user1',
    createdByName: '山田太郎',
    createdAt: '2025-10-08T09:00:00Z',
  },
  {
    id: '5',
    productId: '5',
    noteType: 'general',
    content: '人気商品のため、週末のイベント前に在庫確認を忘れずに。',
    createdBy: 'user2',
    createdByName: '佐藤花子',
    createdAt: '2025-10-06T11:00:00Z',
  },
];

export const stocktakings: Stocktaking[] = [
  {
    id: '1',
    title: '2025年10月 月次棚卸し',
    description: '月次定期棚卸し作業',
    status: 'in_progress',
    startDate: '2025-10-10T09:00:00Z',
    createdBy: 'user1',
    createdByName: '山田太郎',
    createdAt: '2025-10-10T09:00:00Z',
    updatedAt: '2025-10-12T10:30:00Z',
    items: [
      {
        id: '1',
        stocktakingId: '1',
        productId: '1',
        productName: 'キャラクターA フィギュア 限定版',
        productSku: 'A001',
        theoreticalStock: {
          new: 95,
          used: 3,
          damaged: 2,
          total: 100,
        },
        actualStock: {
          new: 94,
          used: 3,
          damaged: 2,
          total: 99,
        },
        difference: {
          new: -1,
          used: 0,
          damaged: 0,
          total: -1,
        },
        notes: '正常在庫1個不足',
        checkedBy: 'user2',
        checkedByName: '佐藤花子',
        checkedAt: '2025-10-12T10:15:00Z',
        status: 'discrepancy',
      },
      {
        id: '2',
        stocktakingId: '1',
        productId: '2',
        productName: 'キャラクターB ぬいぐるみ',
        productSku: 'B002',
        theoreticalStock: {
          new: 18,
          used: 2,
          damaged: 0,
          total: 20,
        },
        actualStock: {
          new: 18,
          used: 2,
          damaged: 0,
          total: 20,
        },
        difference: {
          new: 0,
          used: 0,
          damaged: 0,
          total: 0,
        },
        checkedBy: 'user2',
        checkedByName: '佐藤花子',
        checkedAt: '2025-10-12T10:30:00Z',
        status: 'checked',
      },
      {
        id: '3',
        stocktakingId: '1',
        productId: '4',
        productName: 'キャラクターD クリアファイル',
        productSku: 'D004',
        theoreticalStock: {
          new: 250,
          used: 0,
          damaged: 0,
          total: 250,
        },
        status: 'pending',
      },
      {
        id: '4',
        stocktakingId: '1',
        productId: '5',
        productName: 'キャラクターE アクリルキーホルダー',
        productSku: 'E005',
        theoreticalStock: {
          new: 80,
          used: 0,
          damaged: 0,
          total: 80,
        },
        status: 'pending',
      },
    ],
  },
  {
    id: '2',
    title: '2025年9月 月次棚卸し',
    description: '前月の月次棚卸し作業',
    status: 'completed',
    startDate: '2025-09-10T09:00:00Z',
    endDate: '2025-09-12T17:00:00Z',
    createdBy: 'user1',
    createdByName: '山田太郎',
    createdAt: '2025-09-10T09:00:00Z',
    updatedAt: '2025-09-12T17:00:00Z',
    items: [],
  },
];

export const userRoles: UserRole[] = [
  {
    id: 'admin',
    name: 'admin',
    displayName: 'システム管理者',
    description: '全機能へのフルアクセス権限を持つ',
    permissions: [
      'user_management',
      'master_data_management',
      'product_management',
      'stock_management',
      'stocktaking',
      'reports',
      'system_settings',
    ],
  },
  {
    id: 'manager',
    name: 'manager',
    displayName: 'マネージャー',
    description: '業務統括、レポート分析、承認権限を持つ',
    permissions: [
      'product_management',
      'stock_management',
      'stocktaking',
      'reports',
      'approval',
    ],
  },
  {
    id: 'inventory_manager',
    name: 'inventory_manager',
    displayName: '在庫管理者',
    description: '日常的な在庫管理業務を行う',
    permissions: [
      'product_management',
      'stock_management',
      'stocktaking',
    ],
  },
  {
    id: 'warehouse_worker',
    name: 'warehouse_worker',
    displayName: '倉庫作業員',
    description: '現場での入出庫作業を行う',
    permissions: [
      'stock_movement',
      'stock_check',
    ],
  },
  {
    id: 'sales',
    name: 'sales',
    displayName: '営業担当者',
    description: '在庫情報確認、販売情報閲覧が可能',
    permissions: [
      'product_view',
      'stock_view',
      'sales_info',
    ],
  },
  {
    id: 'viewer',
    name: 'viewer',
    displayName: '閲覧者',
    description: '最小権限（閲覧のみ）',
    permissions: [
      'product_view',
      'stock_view',
    ],
  },
];

export const users: User[] = [
  {
    id: '1',
    username: 'admin',
    email: 'admin@company.com',
    fullName: '管理者 太郎',
    role: 'admin',
    department: 'システム部',
    storageLocationAccess: ['1', '2', '3', '4', '5'],
    isActive: true,
    lastLoginAt: '2025-10-12T08:30:00Z',
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    username: 'yamada',
    email: 'yamada@company.com',
    fullName: '山田 太郎',
    role: 'manager',
    department: '在庫管理部',
    storageLocationAccess: ['1', '2', '3'],
    isActive: true,
    lastLoginAt: '2025-10-12T09:15:00Z',
    createdBy: '1',
    createdByName: '管理者 太郎',
    createdAt: '2024-02-01T10:00:00Z',
    updatedBy: '1',
    updatedByName: '管理者 太郎',
    updatedAt: '2025-10-01T14:30:00Z',
  },
  {
    id: '3',
    username: 'sato',
    email: 'sato@company.com',
    fullName: '佐藤 花子',
    role: 'inventory_manager',
    department: '在庫管理部',
    storageLocationAccess: ['1', '2'],
    isActive: true,
    lastLoginAt: '2025-10-12T07:45:00Z',
    createdBy: '1',
    createdByName: '管理者 太郎',
    createdAt: '2024-02-15T11:00:00Z',
  },
  {
    id: '4',
    username: 'tanaka',
    email: 'tanaka@company.com',
    fullName: '田中 一郎',
    role: 'warehouse_worker',
    department: '倉庫部',
    storageLocationAccess: ['3', '4'],
    isActive: true,
    lastLoginAt: '2025-10-11T16:30:00Z',
    createdBy: '2',
    createdByName: '山田 太郎',
    createdAt: '2024-03-01T09:30:00Z',
  },
  {
    id: '5',
    username: 'suzuki',
    email: 'suzuki@company.com',
    fullName: '鈴木 次郎',
    role: 'sales',
    department: '営業部',
    storageLocationAccess: ['1', '2', '3', '4', '5'],
    isActive: true,
    lastLoginAt: '2025-10-10T13:20:00Z',
    createdBy: '2',
    createdByName: '山田 太郎',
    createdAt: '2024-04-01T10:15:00Z',
  },
  {
    id: '6',
    username: 'watanabe',
    email: 'watanabe@company.com',
    fullName: '渡辺 京子',
    role: 'viewer',
    department: '経理部',
    storageLocationAccess: [],
    isActive: false,
    lastLoginAt: '2025-09-30T17:00:00Z',
    createdBy: '1',
    createdByName: '管理者 太郎',
    createdAt: '2024-05-01T14:00:00Z',
    updatedBy: '1',
    updatedByName: '管理者 太郎',
    updatedAt: '2025-10-01T09:00:00Z',
  },
];

export const reports: Report[] = [
  {
    id: '1',
    name: '在庫サマリーレポート（2025年10月）',
    description: '2025年10月時点での全商品の在庫状況をまとめたレポート',
    type: 'stock_summary',
    parameters: {
      dateRange: {
        start: '2025-10-01T00:00:00Z',
        end: '2025-10-31T23:59:59Z',
      },
    },
    generatedBy: '2',
    generatedByName: '山田 太郎',
    generatedAt: '2025-10-12T09:30:00Z',
    status: 'completed',
    downloadUrl: '/reports/stock-summary-202510.xlsx',
    fileSize: 256000,
  },
  {
    id: '2',
    name: '入出庫履歴レポート（過去30日）',
    description: '過去30日間の入出庫履歴の詳細レポート',
    type: 'movement_history',
    parameters: {
      dateRange: {
        start: '2025-09-13T00:00:00Z',
        end: '2025-10-12T23:59:59Z',
      },
    },
    generatedBy: '3',
    generatedByName: '佐藤 花子',
    generatedAt: '2025-10-12T14:15:00Z',
    status: 'completed',
    downloadUrl: '/reports/movement-history-30days.pdf',
    fileSize: 512000,
  },
  {
    id: '3',
    name: 'アラート履歴レポート（2025年9月）',
    description: '2025年9月に発生したアラートの履歴レポート',
    type: 'alert_history',
    parameters: {
      dateRange: {
        start: '2025-09-01T00:00:00Z',
        end: '2025-09-30T23:59:59Z',
      },
    },
    generatedBy: '2',
    generatedByName: '山田 太郎',
    generatedAt: '2025-10-01T10:00:00Z',
    status: 'completed',
    downloadUrl: '/reports/alert-history-202509.csv',
    fileSize: 128000,
  },
  {
    id: '4',
    name: '棚卸しサマリーレポート（2025年9月）',
    description: '2025年9月の棚卸し結果のサマリーレポート',
    type: 'stocktaking_summary',
    parameters: {
      dateRange: {
        start: '2025-09-01T00:00:00Z',
        end: '2025-09-30T23:59:59Z',
      },
    },
    generatedBy: '2',
    generatedByName: '山田 太郎',
    generatedAt: '2025-10-05T16:45:00Z',
    status: 'completed',
    downloadUrl: '/reports/stocktaking-summary-202509.xlsx',
    fileSize: 384000,
  },
  {
    id: '5',
    name: 'ユーザー活動レポート（生成中）',
    description: '過去1週間のユーザー活動状況レポート',
    type: 'user_activity',
    parameters: {
      dateRange: {
        start: '2025-10-06T00:00:00Z',
        end: '2025-10-12T23:59:59Z',
      },
    },
    generatedBy: '1',
    generatedByName: '管理者 太郎',
    generatedAt: '2025-10-12T15:30:00Z',
    status: 'generating',
  },
];
